title: RGES PIT
email: gaudi.1@osu.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Roman Galactic Exoplanet Survey Project Infrastructure Team (RGES PIT) public website.
github_username: rges-pit
minimal_mistakes_skin: default
search: false

# Canonical site URL configuration
url: https://rges-pit.org
baseurl: ""

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-49YVZVYNP0"
    anonymize_ip: false


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "/assets/images/RST_icon.png"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rges-pit"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
        

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

breadcrumbs: true

sidebar:
  nav: "docs"
